"""
Unit tests for the Switchboard On-Demand oracle-authority target added
2026-09-19 (`chains/solana/scorers.py::score_drift_protocol`'s new
`oracleAuthorityScore` computation, and the new `chains/solana/scripts/
sol_read.py::read_switchboard_pull_feed`/`read_switchboard_queue`
decoders) -- closes METHODOLOGY.md 7's "Add Switchboard On-Demand oracle
authority primitives" open point.

Two things are tested independently of any live RPC call:
  1. `read_switchboard_pull_feed`/`read_switchboard_queue`'s byte-decode
     logic, against the EXACT account bytes fetched live from Solana
     Mainnet Beta on 2026-09-19 (embedded below as a frozen fixture, cross-
     checked byte-identical against a second, independent RPC,
     `solana-rpc.publicnode.com`, before freezing -- see
     `chains/solana/METHODOLOGY.md` section 7's Switchboard entry) --
     frozen so this suite doesn't depend on network access or the feed's
     mutable on-chain state (a price update rewrites `submissions`/
     `result` every slot; `authority`/`queue` do not move on their own).
  2. `score_drift_protocol`'s new oracleAuthorityScore block: the
     feed-authority/queue-authority/program-upgrade three-path minimum,
     using the SAME `_score_full_power_path("squads_v4", ...)` formula
     already calibrated elsewhere in this file -- no new curve invented.

`sol_read.acct` is monkeypatched with the real bytes, same convention as
`test_drift_protocol.py`/`test_solend_governance.py`.
"""
import base64
import importlib.util
import os
import sys
import unittest

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..", "..", "..")

# Exact account bytes, base64, fetched live from https://api.mainnet-beta.solana.com
# on 2026-09-19 (re-read byte-identical against solana-rpc.publicnode.com the
# same day -- see chains/solana/scorers.py::score_drift_protocol's docstring).
# Switchboard On-Demand PullFeedAccountData for Drift's AI16Z spot market oracle
# (BHqLyA9ov1VPNzt8eb5bt75X2Vk1EVKw1d9Qa78Gk5tR).
SWITCHBOARD_FEED_B64 = "xBtsxArX2yhFCf8CT8HJ//Q2uB+9mJUXrbE3zPSOUmGQW4J+r4JdMNL1sRYAAAAA6PWxFgAAAAAASvYoDgxUAAAAAAAAAAAALpfMVf81TeckZOgM4OaoM34N5kCDzkFGM2b2AyJb3tbS9bEWAAAAAOj1sRYAAAAAAEr2KA4MVAAAAAAAAAAAAHG4R8z3czfW2abrPWKX0w65Uck4wYVgVTW7rygjX8Yr0vWxFgAAAADo9bEWAAAAAABK9igODFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP97ESEsVHD8kxWB05L+xWLSvkqGJyEpmDXs0zdP9vOthoBwaEMvGGoUfPCxOjAGfThiBOqdbIsEdDrC7wELB1KLHzeOMOSzLRgias0m8RFff8b6vR8uNSOR6AW3L+afnDucG2kAAAAAAAAAAAAAAAAA8gUqAQAAAAEAAABhaTE2egAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANLnBtpAAAAAJj1sRYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASvYoDgxUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP5J9igODFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEr2KA4MVAAAAAAAAAAAAABK9igODFQAAAAAAAAAAAADAQAAAAAAANL1sRYAAAAA0vWxFgAAAADS9bEWAAAAAJYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS5wbaQAAAABLnBtpAAAAAEucG2kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
# Switchboard On-Demand QueueAccountData for the official default mainnet queue
# (A43DyUGA7s8eXPxqEjJY6EBu1KKbNgfxF8h17VAHn13w, per the SDK's own
# ON_DEMAND_MAINNET_QUEUE constant).
SWITCHBOARD_QUEUE_B64 = "2cI3f7hTigG4gZK0CYjXPEUCA9zlcklrqXNRoFS1kCPxZz6iydpRKQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfc0uGFu5PbJKy9YYNojxyZ/8Zd8T/w73ZC71/5J4XC3dHd8TkvDF9pyadn8ojlYQxw2udAIny5UZhox/8nG/tgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjVICUwzvPj7dy4sy3chtUwR60pwSn0CquSbhGK4Y273G4R8z3czfW2abrPWKX0w65Uck4wYVgVTW7rygjX8YrRQn/Ak/Byf/0NrgfvZiVF62xN8z0jlJhkFuCfq+CXTBJUZ2BBGWX+GxMxSkZWQDqtZi4F6YXWbxUZgkkqEUi6oMA5FxquiaQOe30PIchtfQYzmv0FuSZFhC5AeYRw53OQFpu4Fgem7YDcjLPxzGFkHUvBfdpghqnwYvNLt8pHokd1wLsGCoiPyclWa5/ftrQBFWGauyghwyJRfNCJ6wYRy6XzFX/NU3nJGToDODmqDN+DeZAg85BRjNm9gMiW97Wlg+gbvj8rbPUZUmhXkKbzoEIYsfnoPNPq1r/r+S8htRLFF3TIbFWH2JJEHNcJEDC5DSNgq4uwY+5tl+0shm61cEZes1anu+5GwPKh5Fv6J6c9cAn5XjKlAkhwmWGPkRSrLQTgxoLq/kXx4EyTQ8bMdQtrDYvR6gNqU2rpia7E9sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwuVLyPq7Mft5GD1Jokccx/v6jREQM0J7oWpkcO1uP3pfG22w0gf49TodMDEjNDMNDLNGjRtxLPvNaKfWeYOu/L67aoHjv+eLiIjjufdJizUVdaInMVO0c+oTFpZ3i+WaB19mVS04WAPBr0QnBNUOy25gBwDYbMdH+bDUe37b28rNx250lljKS8/OFf5AgfwhBKuLfRtkJkliiMO+9GWNimR3SNqOPCxXoaV6cGz+oWomJAWf1x0wx19+djfQdfHLLcOHMfJx8gbHH6gG0pZEAccpE2bybFKDVbqgTwBGHJLEYf1NHsW2I7C3XnFUInz1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAu0ScCWMYUyhpUyHCNmaHpQzy2MklPKjKmKuQvFoOqT6nxAqruwTY+Fp0SsRs7jLuGRHtUKAmkkbuvHsrgOZ+aO6M4YbHQFFwO6iF/FfeCaT4csYi5GkikoXD/Hf5/dB155kATP3qrHHGJsEO1dfW2FIP1R1vZVWRjS10yMTLQneM6BZd+dSnQzsZ8p1t4v2r7TNG30MistQLJOGNiz0QxdaKSNdtGnQqZXFzxw4XYEIrEDNyOokUD4T1kILlvXT0dVPEKSJN98rjO5TiAhuKM8O1kL4J04YpQcdBa0NbPmCnRRJmV2ImkDk+Pva+Wxkul8mgUIg+yhKxpqL3aJv9RfN2QzTTmX5mE4hwuyvni+MvW3k2KLapBmFwKglS0CgPdMUpYEqWSNRVaP/kBMMoiTsu3bwyyhO3eWhyo5VAKIfXCUbL+9n/Atgd/wqA90yPbB/HxFb73jZ4Tr7IAg+wLW7ZiaZCfmlO3kSxAsd6o8TJWWdTipKWsMfzHAU9MrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgDoJAAAAAABboq1qAAAAAFgCAAAAAAAAAAAAAAAAAABYAgAAAAAAAAMAAAAMAAAAoLsNAAsAAAAFAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+dbcDwAAAAABAAAAAAAAAAAAAAAAAAAAmIr9t9DrJcjKAWwbdSLvHZz9lCDDvO2KOatUmGE92uEAAAAAAAAAAPPhHO4aPNYHuvXMpXlYYpvTz090jk2RhtVju+InkRbXDQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="

for _name in ("SWITCHBOARD_FEED_B64", "SWITCHBOARD_QUEUE_B64"):
    base64.b64decode(globals()[_name], validate=True)  # fail fast on a corrupted fixture

SBOND_PID = "SBondMDrcV3K4kxZR1HNVT7osZxAHVHgYXL5Ze1oMUv"


def _load_module(unique_name, relative_path):
    file_path = os.path.abspath(os.path.join(REPO_ROOT, relative_path))
    ecosystem_dir = os.path.dirname(file_path)
    if ecosystem_dir not in sys.path:
        sys.path.insert(0, ecosystem_dir)
    spec = importlib.util.spec_from_file_location(unique_name, file_path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[unique_name] = mod
    spec.loader.exec_module(mod)
    return mod


sol_read = _load_module("aro_test_sol_read_switchboard", "chains/solana/scripts/sol_read.py")


class TestReadSwitchboardPullFeed(unittest.TestCase):
    def setUp(self):
        self._orig_acct = sol_read.acct
        sol_read.acct = lambda url, pk, enc="base64", length=None: {
            "data": [SWITCHBOARD_FEED_B64, "base64"], "owner": SBOND_PID}

    def tearDown(self):
        sol_read.acct = self._orig_acct

    def test_discriminator_matches_official_pull_feed_discriminator(self):
        f = sol_read.read_switchboard_pull_feed("unused-url", "unused-pk")
        self.assertTrue(f["discriminator_ok"])

    def test_owner_is_the_on_demand_program(self):
        f = sol_read.read_switchboard_pull_feed("unused-url", "unused-pk")
        self.assertEqual(f["owner"], sol_read.SWITCHBOARD_ON_DEMAND_PROGRAM)

    def test_authority_is_the_real_live_bare_eoa(self):
        f = sol_read.read_switchboard_pull_feed("unused-url", "unused-pk")
        self.assertEqual(f["authority"], "JCHodRTYqK6G5VjqbyD75JNuTFy8o1mFT7j95EXcy7q6")

    def test_queue_is_the_official_default_mainnet_queue(self):
        f = sol_read.read_switchboard_pull_feed("unused-url", "unused-pk")
        self.assertEqual(f["queue"], sol_read.SWITCHBOARD_ON_DEMAND_MAINNET_QUEUE)

    def test_authority_and_queue_do_not_alias_each_other(self):
        # Regression guard for an offset transcription error: authority and
        # queue are two DIFFERENT 32-byte windows (2056:2088 vs 2088:2120)
        # -- if the offsets were accidentally the same or overlapping, both
        # fields would read back identical, which they must not be here.
        f = sol_read.read_switchboard_pull_feed("unused-url", "unused-pk")
        self.assertNotEqual(f["authority"], f["queue"])


class TestReadSwitchboardQueue(unittest.TestCase):
    def setUp(self):
        self._orig_acct = sol_read.acct
        sol_read.acct = lambda url, pk, enc="base64", length=None: {
            "data": [SWITCHBOARD_QUEUE_B64, "base64"], "owner": SBOND_PID}

    def tearDown(self):
        sol_read.acct = self._orig_acct

    def test_discriminator_matches_official_queue_discriminator(self):
        q = sol_read.read_switchboard_queue("unused-url", "unused-pk")
        self.assertTrue(q["discriminator_ok"])

    def test_authority_is_the_real_live_squads_vault_pda(self):
        q = sol_read.read_switchboard_queue("unused-url", "unused-pk")
        self.assertEqual(q["authority"], "DREcTwxxuehtUVgnGwDpTcKT9zTK5uDmdLbnRY7cijEx")


solana = _load_module("aro_test_solana_scorers_switchboard", "chains/solana/scorers.py")


class TestDriftOracleAuthorityScoreSwitchboardOnDemand(unittest.TestCase):
    """Integration test for score_drift_protocol's new oracleAuthorityScore
    block: the feed's own bare-EOA update authority dominates (composite 2)
    even though the shared queue/program layer behind it is a real 3-of-8
    Squads v4 multisig (composite 38 on that path alone) -- the headline
    claim of this addition, verified end to end rather than just unit by
    unit. Drift's program-upgrade path and Realm path are short-circuited
    to the renounced/None case (already covered by
    TestScoreDriftProtocolRenouncedProgramAuthority in
    test_drift_protocol.py) so this test isolates the NEW code path."""

    def setUp(self):
        self._orig_read_program = solana.sol_read.read_program
        self._orig_read_realm = solana.sol_read.read_realm
        self._orig_read_switchboard_pull_feed = solana.sol_read.read_switchboard_pull_feed
        self._orig_read_switchboard_queue = solana.sol_read.read_switchboard_queue
        self._orig_read_keytype = solana.sol_read.read_keytype
        self._orig_read_squads = solana.sol_read.read_squads

        FEED_AUTHORITY = "JCHodRTYqK6G5VjqbyD75JNuTFy8o1mFT7j95EXcy7q6"
        QUEUE_AUTHORITY = "DREcTwxxuehtUVgnGwDpTcKT9zTK5uDmdLbnRY7cijEx"  # real vault-0 of the MS below

        def fake_read_program(url, pk):
            if pk == solana.sol_read.SWITCHBOARD_ON_DEMAND_PROGRAM:
                return {"upgrade_authority": QUEUE_AUTHORITY}
            return {"upgrade_authority": None}  # Drift's own program: renounced, short-circuits

        def fake_read_realm(url, pk):
            return {"community_mint": "DriFtupJYLTosbwoN8koMbEYSx54aFAVLddWsbksjwg7",
                    "council_mint": None, "authority": None, "name": "Drift DAO"}

        def fake_read_switchboard_pull_feed(url, pk):
            return {"feed": pk, "owner": SBOND_PID, "discriminator_ok": True,
                    "authority": FEED_AUTHORITY, "queue": solana.sol_read.SWITCHBOARD_ON_DEMAND_MAINNET_QUEUE,
                    "feed_hash": "ab" * 32}

        def fake_read_switchboard_queue(url, pk):
            return {"queue": pk, "owner": SBOND_PID, "discriminator_ok": True, "authority": QUEUE_AUTHORITY}

        def fake_read_keytype(url, pk):
            if pk == FEED_AUTHORITY:
                return {"key": pk, "on_curve": True, "exists": True, "owner": "11111111111111111111111111111111"}
            return self._orig_read_keytype(url, pk)

        def fake_read_squads(url, pk):
            if pk == "93RQfY6VHRkqXBCEhMY5u92bCGp428DTzqZUEA2Hjr9h":
                # Real, live values (2026-09-19): 3-of-8, all 8 members hold
                # the full Initiate|Vote|Execute mask, autonomous
                # config_authority, no time_lock.
                return {"multisig": pk, "owner": "SQDS4ep65T869zMMBKyuUq6aD6EgTu8psMjkvj52pCf",
                        "config_authority": "11111111111111111111111111111111",
                        "threshold": 3, "time_lock_s": 0, "members": 8,
                        "member_list": [{"key": f"member{i}", "mask": 7} for i in range(8)]}
            raise AssertionError(f"unexpected read_squads call for {pk}")

        solana.sol_read.read_program = fake_read_program
        solana.sol_read.read_realm = fake_read_realm
        solana.sol_read.read_switchboard_pull_feed = fake_read_switchboard_pull_feed
        solana.sol_read.read_switchboard_queue = fake_read_switchboard_queue
        solana.sol_read.read_keytype = fake_read_keytype
        solana.sol_read.read_squads = fake_read_squads

    def tearDown(self):
        solana.sol_read.read_program = self._orig_read_program
        solana.sol_read.read_realm = self._orig_read_realm
        solana.sol_read.read_switchboard_pull_feed = self._orig_read_switchboard_pull_feed
        solana.sol_read.read_switchboard_queue = self._orig_read_switchboard_queue
        solana.sol_read.read_keytype = self._orig_read_keytype
        solana.sol_read.read_squads = self._orig_read_squads

    def test_oracle_authority_score_is_dominated_by_the_bare_eoa_feed_authority(self):
        result = solana.score_drift_protocol("unused-url")
        # feed authority (on_curve) -> (5, 0, 0) -> composite 2
        # queue/program authority (squads_v4 3-of-8, delay=0) -> composite 38
        self.assertEqual(result["oracleAuthorityScore"], 2)

    def test_queue_and_program_paths_reuse_the_existing_squads_v4_formula(self):
        admin, multisig, timelock = solana._score_full_power_path(
            "squads_v4", threshold=3, voters=8, delay_s=0)
        self.assertEqual((admin, multisig, timelock), (50, 60, 0))
        self.assertEqual(solana._composite(admin, multisig, timelock), 38)

    def test_not_a_flat_placeholder_100_anymore(self):
        # Regression guard for the exact bug this addition fixes: every
        # target in this file before 2026-09-19 either computed a real
        # oracleAuthorityScore (Kamino Lend) or hardcoded a flat,
        # unjustified 100 -- Drift was in the second group despite having a
        # real, live, scoreable oracle-authority surface.
        result = solana.score_drift_protocol("unused-url")
        self.assertNotEqual(result["oracleAuthorityScore"], 100)


if __name__ == "__main__":
    unittest.main()
